version: '3.8'

services:
  homepage-dashboard:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-dashboard
    ports:
      - "3000:3000"
    volumes:
      - /home/david/dashboard/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/david/dashboard/icons:/app/public/icons
      - /mnt/WD1:/WD1
      - /mnt/WD2:/WD2
    network_mode: "host"
    restart: "unless-stopped"
    env_file: ./keys.env
