---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Personal:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://old.reddit.com/
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
    - Twitter:
        - abbr: TW
          icon: twitter.png
          href: https://x.com/
    - Messenger:
        - abbr: MS
          icon: /icons/messenger.png
          href: https://www.messenger.com/
    - Facebook:
        - abbr: FB  
          icon: facebook.png
          href: https://facebook.com
    - Gmail:
        - abbr: GM 
          icon: /icons/gmail.png
          href: https://mail.google.com

- Professional:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/Master449?tab=repositories
    - MonkeyTypes:
        - abbr: MT
          icon: /icons/monkeytypes.png
          href: https://monkeytype.com/

- School:
    - OutLook:
        - abbr: OL
          icon: /icons/outlook.png
          href: https://outlook.office.com/mail/inbox
    - BlackBoard:
        - abbr: BB
          icon: /icons/bb.png
          href: https://webcourses.niu.edu/ultra/course
    - MyNIU:
        - abbr: MN
          icon: /icons/myniu.png
          href: https://myniu.niu.edu
    - GitLab:
        - abbr: GL
          icon: gitlab.png
          href: https://gitlab.niu.edu
    - O365:
        - abbr: O3
          icon: microsoft.png
          href: https://o365.niu.edu
