---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.homelab.local
        description: Jellyfin Media Server
        siteMonitor: http://192.168.0.109:8096
        widget:
            type: jellyfin
            url: http://localhost:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true
            enableUser: true
            enableNowPlaying: false
    - Reolink:
        icon: /icons/reolink.png
        href: http://192.168.0.147
        description: NVR PoE Camera System
        ping: http://192.168.0.147
        widget: 
          type: customapi
          url: http://127.0.0.1:1200/api
          refreshInterval: 300000
          method: GET
          mappings:
            - field:
                cameras: garage
              remap:
                - value: 1
                  to: ONLINE
                - value: 0
                  to: OFFLINE
              label: Garage Camera
            - field:
                cameras: house
              remap:
                - value: 1
                  to: ONLINE
                - value: 0
                  to: OFFLINE
              label: House Camera
            - field: disk
              label: Free Space

- Administration:
    - PiHole:
        icon: /icons/pihole.png
        description: Network Wide DNS Ad and Telemetry blocker
        href: http://192.168.0.127/admin/index.php
        ping: http://192.168.0.127/
        widget:
          type: pihole
          url: http://192.168.0.127/
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Uptime Kuma:
        icon: uptime-kuma.png
        description: Uptime Monitor
        href: http://uptime.homelab.local
        ping: http://localhost:7000
        widget:
          type: uptimekuma
          url: http://localhost:7000
          slug: all
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        description: Measures DL/UL
        href: http://speedtest.homelab.local
        ping: http://localhost:4000
        widget:
          type: speedtest
          url: http://localhost:4000


          
- Tailscales:
    - This Machine:
        icon: tailscale.png
        widget:
            type: tailscale
            deviceid: n7JCzBGNnr11CNTRL
            key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}
    - Davids Machine:
        icon: tailscale.png
        widget:
            type: tailscale
            deviceid: nrah1fy3v811CNTRL
            key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}

- Glances:
    - CPU Usage:
        widget:
          type: glances
          url: http://localhost:61208
          metric: cpu
    - Memory Usage:
        widget:
          type: glances
          url: http://localhost:61208
          metric: memory
    - GPU Usage:
        widget:
          type: glances
          url: http://localhost:61208
          metric: gpu:0
