---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.0.109:8096
        description: Jellyfin Media Server
        siteMonitor: http://192.168.0.109:8096
        widget:
            type: jellyfin
            url: http://192.168.0.109:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true
            enableUser: true
            enableNowPlaying: false
    - Transmission:
        icon: transmission.png
        description: Torrent Client
        href: http://torrents.home
        container: torrent-transmission-openvpn-1
        widget:
          type: transmission
          url: http://torrents.home

- Services:
    - Reolink:
        icon: /icons/reolink.png
        href: http://192.168.0.147
        description: NVR PoE Camera System
        ping: http://192.168.0.147
        widget: 
          type: customapi
          url: http://127.0.0.1:1200/api
          refreshInterval: 300000
          method: GET
          mappings:
            - field:
                cameras: garage
              remap:
                - value: 1
                  to: ONLINE
                - value: 0
                  to: OFFLINE
              label: Garage Camera
            - field:
                cameras: house
              remap:
                - value: 1
                  to: ONLINE
                - value: 0
                  to: OFFLINE
              label: House Camera
            - field: disk
              label: Free Space
    - Minecraft Server:
        icon: minecraft.png
        description: NixOS Minecraft Server
        widget:
          type: minecraft
          url: udp://192.168.0.109:25565
    - Bluemap:
        icon: minecraft.png
        description: 3D Minecraft Map Plugin
        href: 192.168.0.109:8100
        ping: 192.168.0.109:8100

- Administration:
    - PiHole:
        icon: /icons/pihole.png
        description: Network Wide DNS Ad and Telemetry blocker
        href: http://192.168.0.127/admin/index.php
        ping: http://192.168.0.127/
        widget:
          type: pihole
          url: http://192.168.0.127/
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Uptime Kuma:
        icon: uptime-kuma.png
        description: Uptime Monitor
        href: http://uptime.home
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://localhost:7000
          slug: all
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        description: Measures DL/UL
        href: http://speedtest.home
        container: speedtest-tracker
        widget:
          type: speedtest
          url: http://localhost:4000
    - UPS Monitor:
        icon: network-ups-tools.png
        description: UPS Monitoring Service
        href: http://192.168.0.109:6001
        container: PeaNUT
        widget:
          type: peanut
          url: http://192.168.0.109:6001
          key: GX1500U
