---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Flowers Dashboard
cardBlur: sm
statusStyle: "dot"
hideVersion: true

layout:
  Media:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
