---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Flowers Dashboard
cardBlur: sm
statusStyle: "dot"
hideVersion: true

layout:
  Router:
    style: row
    columns: 1

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
