---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- openmeteo:
    label: Home
    latitude: {{HOMEPAGE_VAR_LAT}}
    longitude: {{HOMEPAGE_VAR_LON}}
    timezone: America/Chicago
    units: imperial
    cache: 60

#- resources:
    #label: System
    #cpu: true
    #cputemp: true
    #memory: true

#- resources:
    #label: Vault
    #disk:
    #  - /WD1

#- resources:
    #label: Backup
    #disk:
    #  - /WD2

- glances:
    url: http://localhost:61208
    cpu: true
    mem: true
    cputemp: true 
    uptime: true
    disk:
      - /mnt/WD1
      - /mnt/WD2
    diskUnits: bytes 
    expanded: false
    label: Homelab
